baseURL = 'https://thevector.de/'
languageCode = 'de-DE'
title = 'thevector'
theme= "pehtheme-hugo"

summaryLength = '20' # <- 20 words are approximately 160 characters

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Aktuelle IT-News und Blogbeiträge rund um Datenschutz, IT-Security und Technologie – verfasst von IT-Security-Enthusiasten. Frische Perspektiven, fundiertes Wissen und spannende Einblicke in die digitale Welt.'
	mainSections = 'posts'


  [params.authors]

    [params.authors.pius]
      name   = "Pius Werner"
      bio    = "IT-Security Enthusiast"
      avatar = "/images/author/pius.jpg"

    [params.authors.arne]
      name   = "Arne Bauer"
      bio    = "IT-Security Enthusiast"
      # avatar = "/images/author/arne.jpg"

[pagination]
	pagerSize = 6

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'News'
		pageRef = '/tags/News/'
		weight = 15
	[[menu.main]]
		name = 'Datenschutz'
		pageRef = '/tags/Datenschutz/'
		weight = 20
	[[menu.main]]
		name = 'IT-Security'
		pageRef = '/tags/IT-Security/'
		weight = 25
	[[menu.main]]
		name = 'Über uns'
		pageRef = '/posts/about'
		weight = 30

# Taxonomy terms
tags = ['blog', 'responsive', 'light', 'tailwindcss']
features = ['tailwindcss', 'two-column', 'sidebar', 'horizontal-menu']

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'

[related]
  includeNewer = true
  threshold = 60
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 80

  [[related.indices]]
    name = "date"
    weight = 10