matrix:
  - name: Markdown
    expect_match: false
    aspell:
      lang: de        # <--- Sprache auf Deutsch ändern
      d: de_DE       # <--- Deutsches Wörterbuch nutzen
      ignore-case: true # Optional: Hilft bei Groß-/Kleinschreibungs-Mischmasch
      dictionary:
        wordlists:
          - .wordlist.txt
        output: .wordlist.dic
        encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - alt
          ignores:
            - ':matches(code, pre)'
            - 'code'
            - 'pre'
            - 'blockquote'
    sources:
      - 'content/blog/**/*.md'
      - 'content/posts/**/*.md'