name: Spell Check & Grammar

on:
  pull_request:
    paths:
      - 'content/**/*.md'
      - '.spellcheck.yml'
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: Check Spelling
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Spell check with PySpelling
        uses: rojopolis/spellcheck-github-actions@0.23.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown